CREATE TABLE IF NOT EXISTS `#__company` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL,
  `company` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `owner` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `address` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `city` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `usstate` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `zipcode` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `phone` varchar(225) COLLATE latin1_general_cs NOT NULL,
  `email` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `longitute` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `latitude` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `logo` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `featured` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `fkey` int(11) NOT NULL,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enlist` varchar(255) COLLATE latin1_general_cs NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=latin1_general_cs;

CREATE TABLE IF NOT EXISTS `#__employee` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL,
  `employee` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `title` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `phone` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `email` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `url` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `image` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `hours` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `about` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `image` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `fkey` int(11) NOT NULL,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enlist` varchar(255) COLLATE latin1_general_cs NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=latin1_general_cs;

CREATE TABLE IF NOT EXISTS `#__appointment` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL,
  `taxpayer` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `phone` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `email` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `service` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `time` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `notes` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `month` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `day` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `year` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `fkey` int(11) NOT NULL,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enlist` varchar(255) COLLATE latin1_general_cs NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=latin1_general_cs;

CREATE TABLE IF NOT EXISTS `#__email` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL,
  `taxpayer` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `phone` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `email` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `reason` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `images` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `fkey` int(11) NOT NULL,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enlist` varchar(255) COLLATE latin1_general_cs NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=latin1_general_cs;

CREATE TABLE IF NOT EXISTS `#__taxpayer` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`asset_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL,
  `firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `filing_status` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `driver_license` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `issue_date` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `expire_date` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `occupation` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dependents` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_driver_license` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_issue_date` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_expire_date` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `sp_occupation` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `address` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `apartment` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `city` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `usstate` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `zipcode` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `phone` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `email` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_relationship` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep1_student` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep1_disabled` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep2_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep2_midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep2_lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep2_dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep2_ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep2_relationship` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep2_student` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep2_disabled` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep3_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep3_midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep3_lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep3_dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep3_ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep3_relationship` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep3_student` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep3_disabled` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep4_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep4_midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep4_lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep4_dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep4_ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep4_relationship` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep4_student` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep4_disabled` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep5_firstname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep5_midname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep5_lastname` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep5_dob` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep5_ssn` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep5_relationship` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `dep5_student` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dep5_disabled` INT(1) UNSIGNED NOT NULL DEFAULT '0',
  `image` varchar(255) COLLATE latin1_general_cs NOT NULL,
  `fkey` int(11) NOT NULL,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enlist` varchar(255) COLLATE latin1_general_cs NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=latin1_general_cs;

CREATE TABLE IF NOT EXISTS `#__links` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `link` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  `state` tinyint(1) NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__server_config` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `server_ip` varchar(255) NOT NULL,
  `server_dbname` varchar(255) NOT NULL,
  `server_dbusername` varchar(255) NOT NULL,
  `server_dbpassword` varchar(255) NOT NULL,
  `server_droidads` varchar(255) NOT NULL,
  `server_iphoneads` varchar(255) NOT NULL,
  `server_droidbg` varchar(255) NOT NULL,
  `server_iphonebg` varchar(255) NOT NULL,
  `server_droidhome` varchar(255) NOT NULL,
  `server_iphonehome` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  `state` tinyint(1) NOT NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

